# Generated by Django 2.1.5 on 2019-02-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='TodoItem',
        ),
    ]
