# Generated by Django 2.1.7 on 2019-02-27 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190224_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 17, 59, 15, 830681, tzinfo=utc)),
        ),
    ]
